# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
